Update install-script, add divera-plugin
BOSWatch/BW3-Core pull request #92
Opened 2022-01-23 10:11 UTC by lgremme

* Add Divera24/7-Plugin
* Add python3-pip, alsa-utils to install-script;
* Fix install-script to use GIT in boswatch3-folder, use running RTL-FM version
* Add fir_size as optionally value

2022-01-23 11:17 UTC, Schrolli91 requested changes

2022-01-23 11:17 UTC, Schrolli91 commented on plugin/divera.py
> +    def makeRequests(self, apipath, apicall):
Please name internal (private) functions with a leading `_`
eg. `_myFunction()`

2022-01-23 11:17 UTC, Schrolli91 commented on docu/docs/plugin/divera.md
> +Mit diesem Plugin ist es moeglich, Http-Anfragen für Alarmierungen an Divera 24/7 zu senden.
`ö` is allowed, because the docs are in german ;-)

2022-01-23 11:28 UTC, lgremme commented
Änderungen sind eingeflossen.

Ich hatte das Plugin von http.py kopiert und jetzt sind dort ebenfalls die Änderungen enthalten.

2022-02-17 20:00 UTC, lgremme commented
Pytest läuft jetzt ohne Fehler

2022-02-18 06:55 UTC, Schrolli91 requested changes
just some little things - rest LGTM

2022-02-18 06:55 UTC, Schrolli91 commented on boswatch/inputSource/sdrInput.py
> +            if (sdrConfig.get("fir_size") is not None):
to discuss:
`if sdrConfig.get("fir_size", default=None):`

`is not None` is a double negation.

2022-02-18 06:55 UTC, Schrolli91 commented on docu/docs/changelog.md
please remove the changelog changes...
BW3 is not official released till now.

2022-02-19 14:44 UTC, Schrolli91 approved these changes
LGTM

2022-02-19 14:45 UTC, merged